-- Reference schema for the MVP. Runtime table creation is handled by SQLAlchemy.

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(80) UNIQUE NOT NULL,
    user_type VARCHAR(20) NOT NULL,
    email VARCHAR(255) UNIQUE,
    hashed_password TEXT,
    is_active BOOLEAN NOT NULL,
    calorie_target FLOAT NOT NULL,
    protein_target FLOAT NOT NULL,
    carbs_target FLOAT NOT NULL,
    fat_target FLOAT NOT NULL
);

CREATE TABLE sessions (
    session_id VARCHAR(36) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE food_entries (
    entry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) REFERENCES sessions(session_id) ON DELETE SET NULL,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    food_name VARCHAR(140) NOT NULL,
    quantity FLOAT NOT NULL,
    unit VARCHAR(20) NOT NULL,
    calories FLOAT NOT NULL,
    protein FLOAT NOT NULL,
    carbs FLOAT NOT NULL,
    fat FLOAT NOT NULL,
    source VARCHAR(40) NOT NULL,
    logged_on DATE NOT NULL,
    created_at TIMESTAMP NOT NULL
);
