import os

from sqlalchemy import create_engine, event, text
from sqlalchemy.orm import declarative_base, sessionmaker


DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./macro_tracker.db")

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, connect_args=connect_args)

if DATABASE_URL.startswith("sqlite"):
    @event.listens_for(engine, "connect")
    def enable_sqlite_foreign_keys(dbapi_connection, _connection_record):
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()

SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)
Base = declarative_base()


POSTGRES_IDENTITY_COLUMNS = (
    ("users", "user_id"),
    ("food_entries", "entry_id"),
)


def initialize_database():
    """Create new tables and repair early MVP tables missing PostgreSQL identities."""
    Base.metadata.create_all(bind=engine)

    if engine.dialect.name != "postgresql":
        return

    with engine.begin() as connection:
        for table_name, column_name in POSTGRES_IDENTITY_COLUMNS:
            identity_generation = connection.execute(
                text(
                    """
                    SELECT identity_generation
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = :table_name
                      AND column_name = :column_name
                    """
                ),
                {"table_name": table_name, "column_name": column_name},
            ).scalar_one_or_none()

            if identity_generation is None:
                connection.execute(
                    text(
                        f'ALTER TABLE "{table_name}" '
                        f'ALTER COLUMN "{column_name}" '
                        "ADD GENERATED BY DEFAULT AS IDENTITY"
                    )
                )


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
